### ISSUE TITLE
与notebook主题不兼容

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/mobile-imessage-layout#12]
桌面端会显示`Overwritten by[$:/themes/nico/notebook]so that the default sidebar does not get rendered.`，然后刷新一下就会出现报错。移动端则是直接弹出报错提示。

![image](https://github.com/tiddly-gittly/mobile-imessage-layout/assets/109711900/cc281651-0677-450d-ba72-53b1402b7b04)

![image](https://github.com/tiddly-gittly/mobile-imessage-layout/assets/109711900/1b58274a-5213-4cec-bfdf-bf471badb935)

可能是felixhayashi/hotzone插件影响了。

应该不是什么大问题，但在移动端一使用，就会弹出报错提示。

**Comment by dongrentianyu** [comment]
当切回正常页面时，就不会弹出报错窗口了。

**Comment by linonetwo** [comment]
Hotzone 插件得卸载了，现在都改用 Gk0Wk/focused-tiddler 了 https://tw-cpl.netlify.app/#Plugin_202301155334595

它太老了，不支持任何 layout 功能

**Comment by dongrentianyu** [comment]
卸载了Hotzone 插件后，就只会提示`Overwritten by[$:/themes/nico/notebook]so that the default sidebar does not get rendered.`而不会弹报错了。

**Comment by linonetwo** [comment]
我更新了样式，可能修复了

还有我在 CPL 里没看到 notebook 主题呀

**Comment by linonetwo** [comment]
我在这里面隐藏了侧边栏，所以应该是修复了

**Comment by dongrentianyu** [comment]
> 我更新了样式，可能修复了
> 
> 还有我在 CPL 里没看到 notebook 主题呀

对，因为原来的链接出了问题，仓库也出了问题，后面社区就上传了一个备份的网址。

https://saqimtiaz.github.io/sq-tw/notebook.html

我还给那个作者发过邮件提醒他，但他好像没注意看，也没修复。

https://nicolas.petton.fr/tw/notebook.html

这是原来的网址，现在只有作者的一张头像图片了，其他啥也没了。

CPL这个问题之前我好像跟sttot说过，但估计也没改。
